### ISSUE TITLE
Qwiic is trademarked

### ISSUE THREAD

**Issue by FreezeS** [wagiminator/ATtiny412-I2C-Rotary-Encoder#1]
Hi,

Just to let you know that the brand "Qwiic" is trademarked so you might receive a trademark infringement notification: https://uspto.report/TM/88099558
Sparkfun might be legally forced to send the Cease and Desist otherwise they might lose their trademark.

We called our connectors "I2C 3V3" to avoid this.

**Comment by wagiminator** [comment]
Hi,
thank you for the hint. I've replaced it with "I2C".
